### ISSUE TITLE
网页端 很多场次都无法抢 只能在app上

### ISSUE THREAD

**Issue by ckr2337871271** [WECENG/ticket-purchase#1]
佬 整个app的

**Comment by WECENG** [comment]
后续考虑优化

在 2023-10-12 16:42:19，ckr2337871271 ***@***.***> 写道：


佬 整个app的

**Comment by nieboye** [comment]
附议

**Comment by WECENG** [comment]
已解决 https://github.com/WECENG/ticket-purchase#%E5%A4%A7%E9%BA%A6app%E6%8A%A2%E7%A5%A8
