### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by cn-Meepo** [WECENG/ticket-purchase#11]
io.appium.uiautomator2.common.exceptions.StaleElementReferenceException: Cached elements 'By.id: tv_tour_city' do not exist in DOM anymore  请问下这个是怎么回事啊？

![image](https://github.com/WECENG/ticket-purchase/assets/28797329/fd417ddf-b092-48fd-873e-7ef70e86dee4)

**Comment by WECENG** [comment]
这是因为你要抢到票不需要选择城市，这个异常不会影响主流程

**Comment by cn-Meepo** [comment]
可是这个报错之后就直接退出了

**Comment by cn-Meepo** [comment]
![image](https://github.com/WECENG/ticket-purchase/assets/28797329/ffe0c0d6-2e39-401b-b1cb-6ca6fe6edd32)
大佬，我打断点发现这个里面是空的，但其实人员列表我有填写的

**Comment by WECENG** [comment]
大麦app里的常用观演人要提前填好

**Comment by cn-Meepo** [comment]
可以了，原来那个抓取的只能是页面可是范围内的，如果填的人多了，要选择的人要往下拉才能看到那种就选不了

**Comment by WECENG** [comment]
咦～这是个问题，后续考虑优化

**Comment by cn-Meepo** [comment]
大佬，这个抢票速度感觉有点慢啊，能不能优化下

**Comment by WECENG** [comment]
@cn-Meepo 目前已在优化
