### ISSUE TITLE
演唱会开抢倒计时时抛出异常

### ISSUE THREAD

**Issue by DDSXin** [WECENG/ticket-purchase#16]
![image](https://github.com/WECENG/ticket-purchase/assets/131854184/117f9867-1353-41fe-95f4-7e850591152c)

**Comment by DDSXin** [comment]
![image](https://github.com/WECENG/ticket-purchase/assets/131854184/ae796c23-ba55-403d-a20e-4f2cf799e747)

**Comment by WECENG** [comment]
重新连接USB

**Comment by DDSXin** [comment]
![image](https://github.com/WECENG/ticket-purchase/assets/131854184/8805cd4c-9742-426c-81cf-adc1d895811a)

**Comment by DDSXin** [comment]
这个过程没有USB参与啊

**Comment by WECENG** [comment]
那应该是浏览器驱动的问题

**Comment by WECENG** [comment]
你用的什么浏览器

**Comment by DDSXin** [comment]
chrome

**Comment by WECENG** [comment]
装个最新驱动试试

**Comment by DDSXin** [comment]
![image](https://github.com/WECENG/ticket-purchase/assets/131854184/405d9110-3179-44f1-b9ec-2c921977b58b)

**Comment by DDSXin** [comment]
我debug了一下。buy_button=="预约抢票"好像没处理，但应该不是这里造成的，我看程序还在跑，这个异常好像不影响程序在运行，但是中间没有print信息，可以加一下，不然感觉好像挂了一样。。。。

**Comment by WECENG** [comment]
好的，后续优化

**Comment by WECENG** [comment]
感谢提出问题
