### ISSUE TITLE
app端找不到立即购买报错了

### ISSUE THREAD

**Issue by wahh159** [WECENG/ticket-purchase#24]
![image](https://github.com/WECENG/ticket-purchase/assets/34958368/e9232a59-fc8f-4faa-ad47-19b361846a12)
![image](https://github.com/WECENG/ticket-purchase/assets/34958368/c109839b-6b36-47f7-913c-1ec361ffb4c7)

**Comment by WECENG** [comment]
应该是app更新了

**Comment by WECENG** [comment]
获取不到了，大麦app更新了，换成其它定位方式

**Comment by wahh159** [comment]
坐标可以

> 我用 appium inspector 查看发现购买按钮的 text 是空字符串，请问有没有什么办法可以再获取到？ @WECENG

**Comment by Raffaellorr** [comment]
大佬可以具体说说吗，appium 我还不是很熟练
