### ISSUE TITLE
抢到票啦

### ISSUE THREAD

**Issue by unclewei** [WECENG/ticket-purchase#30]
好消息，抢到票啦
![IMG_5525](https://github.com/WECENG/ticket-purchase/assets/18069781/a657436e-741e-410d-9750-874979018948)

坏消息，手动抢的；😈

**Comment by codeNiuMa** [comment]
？？？

**Comment by unclewei** [comment]
邮件已收到，谢谢。我会尽快回复您。祝您生活愉快。your email has been received, thank you. I will reply you as soon as possible. Have a nice day！
