### ISSUE TITLE
作者 求答疑 配置很久了 配置完appuim 运行项目 还是一样网页抢票 没有app抢票啊

### ISSUE THREAD

**Issue by 331797832** [WECENG/ticket-purchase#31]
需要下载模拟器吗 appuim面板也需要下载吗？ 我下载了一个雷电模拟器这样 
![QQ截图20240120221429](https://github.com/WECENG/ticket-purchase/assets/157223646/b225f7ed-6f26-4a21-b46d-3c0531049989)
![QQ截图20240120221523](https://github.com/WECENG/ticket-purchase/assets/157223646/f119eff3-b61f-4306-a001-faccb248505d)

**Comment by miku1130** [comment]
你运行错程序了。。
