### ISSUE TITLE
选定城市

### ISSUE THREAD

**Issue by Typnose** [WECENG/ticket-purchase#38]
想问一下，没有选定城市，config填了空 但是一直卡在选定城市这里 怎么办
<img width="1228" alt="image" src="https://github.com/WECENG/ticket-purchase/assets/86584310/63a745a7-4943-4674-b112-84438c1c3905">

**Comment by WECENG** [comment]
你改了代码吧，print()后面没有self.config.city的

**Comment by Typnose** [comment]
> 你改了代码吧，print()后面没有self.config.city的

哦哦 那个是上面想打印一下 结果没写对后面又删除了

**Comment by WECENG** [comment]
不选城市，会默认选中，不影响脚本运行逻辑
