### ISSUE TITLE
虚心求教，请问一下大佬是怎么看到大麦页面app代码的

### ISSUE THREAD

**Issue by starCooking** [WECENG/ticket-purchase#39]
![微信图片_20240224204742](https://github.com/WECENG/ticket-purchase/assets/125279535/428661bc-9997-4d93-8685-0bc7358d1637)
类似于这样的节点，是反编译apk看的吗，还是有某种方式捕获

**Comment by WECENG** [comment]
我用的是appium inspector

**Comment by starCooking** [comment]
> 我用的是appium inspector

感谢大佬，还有就是想请问一下大佬是用模拟器操作还是接真机，还有就是大麦的滑动验证是怎么绕过的

**Comment by WECENG** [comment]
真机，滑动认证模拟手动滑动
