### ISSUE TITLE
大佬能看看嘛，卡住了，今天就是邓紫棋的票了

### ISSUE THREAD

**Issue by ljt990218** [WECENG/ticket-purchase#40]
我有开mumu模拟器和studio的模拟器
![QQ截图20240228043852](https://github.com/WECENG/ticket-purchase/assets/50509815/03daea79-48df-4f2a-8b3a-1dcc47bf6058)

**Comment by ljt990218** [comment]
我有 uiautomator2@3.0.1 插件
运行 appium --use-plugins uiautomator2 的时候却提示未安装
![Uploading QQ截图20240228044221.png…]()

**Comment by WECENG** [comment]
先安装uiautomator2驱动，用npm install appium-uiautomator2-driver命令

**Comment by ljt990218** [comment]
![QQ截图20240228133803](https://github.com/WECENG/ticket-purchase/assets/50509815/ffa9a1e0-21d2-45f2-a29c-7fa68b91096e)
安装了的

**Comment by sclsx** [comment]
我也是这个问题，兄弟解决了吗

**Comment by ljt990218** [comment]
> 我也是这个问题，兄弟解决了吗

没有😭

**Comment by ljt990218** [comment]
https://github.com/WECENG/ticket-purchase/issues/41 解决了我的问题

**Comment by ljt990218** [comment]
https://github.com/WECENG/ticket-purchase/issues/41 解决了我的问题

**Comment by lghItem** [comment]
uiautomator2 使用命令“appium server”即可
