### ISSUE TITLE
有没有大佬看看问题，安装了appium-uiautomator2-driver且没有报错，但是下一步的时候提示没有安装uiautomator2是为什么

### ISSUE THREAD

**Issue by sclsx** [WECENG/ticket-purchase#41]
![Snipaste_2024-03-01_01-18-22](https://github.com/WECENG/ticket-purchase/assets/101981251/6b44cded-515f-48b5-b570-53dbd03f7638)

**Comment by tiexo** [comment]
一样的问题

**Comment by liluq** [comment]
不要用npm install，用appium driver install uiautomator2
启动的时候用appium --use-drivers uiautomator2

**Comment by rookie-life** [comment]
我也是这样，我按liluq大佬的方式就好了，而且我指定uiautomator2的版本@2.32.3。   但是我小米好像没开root  烦死

**Comment by sclsx** [comment]
> 我也是这样，我按liluq大佬的方式就好了，而且我指定uiautomator2的版本@2.32.3。 但是我小米好像没开root 烦死

已经放弃了，还是手动抢吧，大佬如果能成功抢到的话踢我一下，我要看的演唱会在下半年，如果能用我之后再试试

**Comment by rookie-life** [comment]
我也放弃了。appium命令行安装坑的地方太多，版本不一样就可能跑不通。以后有时间直接用客户端版的appium吧，网上教程很多。

**Comment by rookie-life** [comment]
刚说完就跑通了，还要安装jdk。。。。不然我一直卡在appium app闪退。离谱。等这两天抢一下试试

**Comment by sclsx** [comment]
> 刚说完就跑通了，还要安装jdk。。。。不然我一直卡在appium app闪退。离谱。等这两天抢一下试试

等你的好消息！

**Comment by rookie-life** [comment]
。。。控件名字不一样了。要用appium inspector再看看。。。唉

**Comment by rookie-life** [comment]
有滑动验证的。。最终还是靠手

**Comment by Karyll-star** [comment]
> 不要用npm install，用appium driver install uiautomator2 启动的时候用appium --use-drivers uiautomator2

赞赞赞

**Comment by chensisn** [comment]
> 有滑动验证的。。最终还是靠手

所以最后还是上手抢到的吗？我11月有票要抢
