### ISSUE TITLE
网页版大麦抢票，在config中写了两个user，但是运行后每次的订单都只有一张票是为什么，急，求解答！

### ISSUE THREAD

**Issue by youyumeimei** [WECENG/ticket-purchase#43]
![B9BABF5BDDD122D2DB7ADCE7CD7F6D3D](https://github.com/WECENG/ticket-purchase/assets/64399063/83b93622-3f76-4242-8b9e-a46f5b983c41)
![E91C37F59CAF5A59E934D369968DDD8A](https://github.com/WECENG/ticket-purchase/assets/64399063/7804df56-ba1d-430d-932b-6b6b97eee445)

**Comment by youyumeimei** [comment]
并且设置的price好像也是无效了，都是默认的一个价格的票

**Comment by WECENG** [comment]
是不是名字没写对，断点看一下

**Comment by WECENG** [comment]
那你得自己调一下程序，不同页面可能dom元素不一致

**Comment by 13835971862** [comment]
> ![B9BABF5BDDD122D2DB7ADCE7CD7F6D3D](https://private-user-images.githubusercontent.com/64399063/310474614-83b93622-3f76-4242-8b9e-a46f5b983c41.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjczNDgsIm5iZiI6MTcxNDcyNzA0OCwicGF0aCI6Ii82NDM5OTA2My8zMTA0NzQ2MTQtODNiOTM2MjItM2Y3Ni00MjQyLThiOWUtYTQ2ZjViOTgzYzQxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDA5MDQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNzMxYzNhOTE3N2ZjMzE5ZTk2MDgxOTkwMjg0ZGVmZDcyNjBhOGM3ODliZDk0ZTA2N2RhOTkxNjkxYmI0ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m_VpRYHpzlZkc7ZrYW0F6Xppy2xLPBB5GX_lcFoIxU0) ![E91C37F59CAF5A59E934D369968DDD8A](https://private-user-images.githubusercontent.com/64399063/310474625-7804df56-ba1d-430d-932b-6b6b97eee445.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjczNDgsIm5iZiI6MTcxNDcyNzA0OCwicGF0aCI6Ii82NDM5OTA2My8zMTA0NzQ2MjUtNzgwNGRmNTYtYmExZC00MzBkLTkzMmItNmI2Yjk3ZWVlNDQ1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDA5MDQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwODRjNTExNmFiMTFiZTZkMzA0ZDRlZTYzZWVhNGE3ZmUzOTY4YWUxZGRiMDVjNGE4YWMzYzY1NjkzNjM2Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1NKxikOxM-5XpEor16JvknqRpJEvtg4AwLRoa126jt0)

我也遇到了一样的问题，请问大佬解决了吗？
