### ISSUE TITLE
请问作者是怎么绕过滑块验证的？这块有兄弟懂的吗？

### ISSUE THREAD

**Issue by 1993226871** [WECENG/ticket-purchase#47]

**Comment by rookie-life** [comment]
我今天弄了一天。。环境安装坑太多了，而且adb想控制小米手机还要踩好多设置的坑。最后我看daima_app.py里也没有滑块验证啊。逻辑就是不停检查按钮，如果是立即购买，就点击。然后就没有了，提交订单都没有....那我直接python定时到点，用adb固定点击右下角1s也是一样的。。。如果我理解错了，望作者反驳

**Comment by rookie-life** [comment]
appium想控制小米要踩很多坑。adb倒是很方便，能连通就能模拟点击

**Comment by rookie-life** [comment]
如果要绕过滑块，最好自己拟合一个人的滑动曲线函数，然后让脚本在短时间内滑过去应该就可以。

**Comment by 1993226871** [comment]
> 如果要绕过滑块，最好自己拟合一个人的滑动曲线函数，然后让脚本在短时间内滑过去应该就可以。

但是作者的代码里面我没有看到相关的操作啊，不理解怎么做到的

**Comment by 1993226871** [comment]
> 如果要绕过滑块，最好自己拟合一个人的滑动曲线函数，然后让脚本在短时间内滑过去应该就可以。

另外页面不需要反复刷新吗？没有看到有self.driver.refresh()的操作，还是说有其他函数代替了这个呢？又或者浏览器本身就在不断刷新，不需要手动刷新？

**Comment by WECENG** [comment]
滑动认证需要模拟滑动曲线函数。试过了，但是成功率并不高，建议尽量避免滑动认证出现。

**Comment by rookie-life** [comment]
可是怎么避免呢大大。今天就被滑动验证卡了。即使手抢，大麦app也是很容易给滑块验证

**Comment by miku1130** [comment]
> 可是怎么避免呢大大。今天就被滑动验证卡了。即使手抢，大麦app也是很容易给滑块验证

纯看命

**Comment by 1993226871** [comment]
> 可是怎么避免呢大大。今天就被滑动验证卡了。即使手抢，大麦app也是很容易给滑块验证

大哥，问一下，我安装了sdk manager，但是里面最高只有os 10的版本，但是模拟器现在都是os12了，请问这个怎么解决呢？

**Comment by 1993226871** [comment]
您好，我已收到您的邮件。
