### ISSUE TITLE
求教，调试之后用app跑起来速度很慢

### ISSUE THREAD

**Issue by Hart-Lin** [WECENG/ticket-purchase#54]
大佬礼貌求教，调试之后用app跑起来速度很慢啊，感觉还不如手操，请问这样真的可以抢到吗，或者说有好的解决办法？

**Comment by WECENG** [comment]
网页版比较靠谱🙈

**Comment by Hart-Lin** [comment]
不过网页现在逐渐关闭了，感觉可能再往后面可能会没有这个抢票窗口了😇
