### ISSUE TITLE
最后提交订单

### ISSUE THREAD

**Issue by Weeeus** [WECENG/ticket-purchase#6]

**Comment by Weeeus** [comment]
is:issue is:open ***开始确认订单***  Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="dmOrderSubmitBlock_DmOrderSubmitBlock"]/div[2]/div/div[2]/div[3]/div[2]/span"}   (Session info: chrome=118.0.5993.118)   大佬这个是什么原因

**Comment by Summer-Row** [comment]
同问，也遇到了这个问题

**Comment by WECENG** [comment]
已更新修复
