### ISSUE TITLE
readme 命令错误

### ISSUE THREAD

**Issue by yuqiang1999** [WECENG/ticket-purchase#7]
![image](https://github.com/WECENG/ticket-purchase/assets/55423664/ef424289-2c61-4ff0-9a0e-b078b44768bc)
如上，应该是 appium-python-client-3.1.0 吧

**Comment by WECENG** [comment]
对，写错了


| |
werson
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年10月30日 11:41 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [WECENG/ticket-purchase] readme 命令错误 (Issue #7) |


如上，应该是 appium-python-client-3.1.0 吧

**Comment by yuqiang1999** [comment]
[ADB] Getting connected devices
[ADB] No connected devices have been detected
[ADB] Could not find online devices
[ADB] Reconnecting adb (target offline)
[ADB] Running '/Users/yuqiang/Library/Android/sdk/platform-tools/adb -P 5037 reconnect offline'
[AndroidUiautomator2Driver@267e (d1b254ab)] Deleting UiAutomator2 session
[AndroidUiautomator2Driver@267e (d1b254ab)] Unable to stop ChromeDriver proxies: Cannot read properties of undefined (reading 'proxyReqRes')
[AppiumDriver@4929] Event 'newSessionStarted' logged at 1698646418153 (14:13:38 GMT+0800 (中国标准时间))
[AppiumDriver@4929] Encountered internal error running command: Error: Could not find a connected Android device in 20000ms

**Comment by WECENG** [comment]
没有识别到你的android设备，用adb命令查看你的可用设备


| |
werson
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年10月30日 14:16 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [WECENG/ticket-purchase] readme 命令错误 (Issue #7) |

[ADB] Getting connected devices
[ADB] No connected devices have been detected
[ADB] Could not find online devices
[ADB] Reconnecting adb (target offline)
[ADB] Running '/Users/yuqiang/Library/Android/sdk/platform-tools/adb -P 5037 reconnect offline'
***@***.*** (d1b254ab)] Deleting UiAutomator2 session
***@***.*** (d1b254ab)] Unable to stop ChromeDriver proxies: Cannot read properties of undefined (reading 'proxyReqRes')
***@***.*** Event 'newSessionStarted' logged at 1698646418153 (14:13:38 GMT+0800 (中国标准时间))
***@***.*** Encountered internal error running command: Error: Could not find a connected Android device in 20000ms

**Comment by yuqiang1999** [comment]
![image](https://github.com/WECENG/ticket-purchase/assets/55423664/a9cce271-c9d6-4cf9-bb6a-b01264d9968f)
An unknown server-side error occurred while processing the command. Original error: Cannot start the 'cn.damai' application. Consider checking the driver's troubleshooting documentation. Original error: Activity name '.launcher.splash.SplashMainActivity' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
创建了这个模拟器之后再跑 报这个错了😂

**Comment by WECENG** [comment]
模拟器没有大麦app应用，用安装好大麦app的真机测试吧


| |
werson
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年10月30日 14:49 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [WECENG/ticket-purchase] readme 命令错误 (Issue #7) |


An unknown server-side error occurred while processing the command. Original error: Cannot start the 'cn.damai' application. Consider checking the driver's troubleshooting documentation. Original error: Activity name '.launcher.splash.SplashMainActivity' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
创建了这个模拟器之后再跑 报这个错了😂
